name: CI/CD

on:
    push:
        branches: ["main", "staging"]

jobs:
    build-and-deploy:
        uses: rhaversen/.github/.github/workflows/ci-cd.yml@main
        with:
            project_name: "DupontdokuBackend"
            dockerhub_image_name: "dupontdoku-backend"
            node_version: "24"
            push_sourcemaps: false
        secrets:
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
            DEVOPS_REPO_TOKEN: ${{ secrets.DEVOPS_REPO_TOKEN }}
